[package]
name = "htesterp"
version = "0.1.0"
authors = ["Zer1t0"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
reqwest = "0.10"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"